alter type public.inventory_movement_type add value if not exists 'adjustment';
create type public.inventory_adjustment_status as enum ('pending', 'confirmed');
create table public.inventory_adjustments (
 id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict, variant_id uuid not null, expected_quantity integer not null, counted_quantity integer not null check(counted_quantity>=0), quantity_delta integer not null check(quantity_delta<>0), reason text not null check(char_length(btrim(reason)) between 3 and 300), status public.inventory_adjustment_status not null default 'pending', request_id uuid not null, counted_by uuid not null references auth.users(id), counted_at timestamptz not null default now(), confirmed_by uuid references auth.users(id), confirmed_at timestamptz,
 constraint inventory_adjustments_variant_business foreign key(variant_id,business_id) references public.product_variants(id,business_id) on delete restrict, constraint inventory_adjustments_request_unique unique(business_id,request_id), constraint inventory_adjustments_confirmation check((status='pending' and confirmed_by is null and confirmed_at is null)or(status='confirmed' and confirmed_by is not null and confirmed_at is not null))
);
alter table public.inventory_adjustments enable row level security;
create policy "owners or counters read adjustments" on public.inventory_adjustments for select to authenticated using(public.is_business_owner(business_id) or counted_by=auth.uid());
create function public.record_inventory_count_difference(p_business_id uuid,p_variant_id uuid,p_counted_quantity integer,p_reason text,p_request_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare adjustment_id uuid; expected integer; begin if auth.uid() is null or not public.has_business_permission(p_business_id,'inventory.read') then raise exception 'No tienes permiso para registrar conteos.'; end if; select id into adjustment_id from public.inventory_adjustments where business_id=p_business_id and request_id=p_request_id; if adjustment_id is not null then return adjustment_id; end if; if p_counted_quantity is null or p_counted_quantity<0 then raise exception 'La cantidad contada no es válida.'; end if; select coalesce(sum(quantity_delta),0)::integer into expected from public.inventory_movements where business_id=p_business_id and variant_id=p_variant_id and inventory_state='available'; if expected=p_counted_quantity then raise exception 'El conteo no tiene diferencia.'; end if; insert into public.inventory_adjustments(business_id,variant_id,expected_quantity,counted_quantity,quantity_delta,reason,request_id,counted_by) values(p_business_id,p_variant_id,expected,p_counted_quantity,p_counted_quantity-expected,btrim(p_reason),p_request_id,auth.uid()) returning id into adjustment_id; if public.is_business_owner(p_business_id) then perform public.confirm_inventory_adjustment(p_business_id,adjustment_id,gen_random_uuid()); end if; return adjustment_id; end; $$;
create function public.confirm_inventory_adjustment(p_business_id uuid,p_adjustment_id uuid,p_request_id uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare row public.inventory_adjustments%rowtype; begin if auth.uid() is null or not public.has_business_permission(p_business_id,'inventory.adjust') then raise exception 'No tienes permiso para confirmar ajustes.'; end if; select * into row from public.inventory_adjustments where id=p_adjustment_id and business_id=p_business_id for update; if not found then raise exception 'El ajuste no está disponible.'; end if; if row.status='confirmed' then return row.id; end if; insert into public.inventory_movements(business_id,variant_id,movement_type,inventory_state,quantity_delta,source_type,source_id,occurred_at,created_by) values(p_business_id,row.variant_id,'adjustment','available',row.quantity_delta,'inventory_adjustment',row.id,now(),auth.uid()); update public.inventory_adjustments set status='confirmed',confirmed_by=auth.uid(),confirmed_at=now() where id=row.id; return row.id; end; $$;
revoke all on function public.record_inventory_count_difference(uuid,uuid,integer,text,uuid) from public; grant execute on function public.record_inventory_count_difference(uuid,uuid,integer,text,uuid) to authenticated;
revoke all on function public.confirm_inventory_adjustment(uuid,uuid,uuid) from public; grant execute on function public.confirm_inventory_adjustment(uuid,uuid,uuid) to authenticated;
